//
//  AccountCloseViewController.swift
//  ViperExample
//
//  Created by Merve on 24.09.2019.
//  Copyright (c) 2019 Merve Sahan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AccountCloseViewController: BaseViewController {
    
    
    var presenter: AccountClosePresenterProtocol!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        initViews()
        presenter?.getAllRates()
    }
    
    func initViews(){
        
      
        
    }
    
}

extension AccountCloseViewController : AccountCloseViewProtocol {
    
    func reloadData() {
       // allRatesTableView.isHidden = false
        //self.allRatesTableView.reloadData()
    }
    
}

